version: '2'
services:
    jdemo-app:
        image: jdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jdemo-mysql:3306/jdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jdemo-mysql:
        extends:
            file: mysql.yml
            service: jdemo-mysql
